#!/bin/bash

# A function to test the sanity of the PEM private key file
# generated by ssh-keygen
function test_ssh_key {
    openssl rsa -inform PEM -in "$1" -noout &> /dev/null
    if [ $? != 0 ]; then
        printf "The generated key either isn't readable, doesn't exist or is invalid\n"
        exit 1
    fi
}

# Default AWS region
awsRegion=""

# Parse command-line arguments
while [[ "$#" -gt 0 ]]; do
    case $1 in
        -r|--region) awsRegion="$2"; shift ;;
        *) echo "Unknown parameter passed: $1"; exit 1 ;;
    esac
    shift
done

# Set the key pair name
read -p "Enter the name for the AWS key pair: " keyPairName

# Check if the key pair name is empty
if [ -z "$keyPairName" ]; then
    echo "Key pair name cannot be empty."
    exit 1
fi

# Directory where the script is located
scriptDir="$(pwd)"

# File names for the private and public key
privateKeyFile="$scriptDir/${keyPairName}.pem"
publicKeyFile="$privateKeyFile.pub"

# Check if the key already exists
if [ -f "$privateKeyFile" ]; then
    echo "Key pair already exists. Skipping key generation."
else
    # Generate the key pair
    ssh-keygen -m PEM -f "$privateKeyFile"

    # Check if key generation was successful
    if [ ! -f "$privateKeyFile" ]; then
        echo "Key pair generation failed."
        exit 1
    fi

    # Protect the private key
    chmod 400 "$privateKeyFile"

    # Verify the key is well produced
    test_ssh_key "$privateKeyFile"
fi

# Upload the public key to AWS
if [ ! -z "$awsRegion" ]; then
    printf "Key will be populated in the $awsRegion region in your AWS CLI config\n"
    aws ec2 import-key-pair --region "$awsRegion" --key-name "$keyPairName" --public-key-material fileb://"$publicKeyFile"
else
    printf "Key will be populated in the default region in your AWS CLI config\n"
    aws ec2 import-key-pair --key-name "$keyPairName" --public-key-material fileb://"$publicKeyFile"
fi

# Check if AWS CLI command was successful
if [ $? -ne 0 ]; then
    echo "Failed to upload the key pair to AWS."
    exit 1
else
    echo "Key pair uploaded successfully to AWS."
fi
